// Bundles the API into the Supabase Edge Function "training"
// (supabase/functions/training/index.js), deployed with
// `supabase functions deploy training`.
import { build } from "esbuild";

await build({
  entryPoints: ["src/edge.ts"],
  outfile: "../supabase/functions/training/index.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "es2022",
  minify: true,
  sourcemap: false,
  legalComments: "none",
  // Optional native/browser-only modules the server never loads
  external: ["pg-native", "canvg", "html2canvas", "dompurify"],
  banner: {
    js: [
      "// Generated by training-api/build.mjs. Do not edit; change training-api/src and rebuild.",
      'import { createRequire as __createRequire } from "node:module";',
      'import __process from "node:process";',
      'import { Buffer as __Buffer } from "node:buffer";',
      'import { setImmediate as __setImmediate, clearImmediate as __clearImmediate } from "node:timers";',
      "const require = __createRequire(import.meta.url);",
      "globalThis.global ??= globalThis;",
      "globalThis.process ??= __process;",
      "globalThis.Buffer ??= __Buffer;",
      "globalThis.setImmediate ??= __setImmediate;",
      "globalThis.clearImmediate ??= __clearImmediate;",
    ].join("\n"),
  },
  logLevel: "info",
});
